const MAX_WIDTH = 1280;
const MIDDLE_WIDTH = 768; 
const PORTION_MIN = 2;
const PORTION_MAX = 3;
const INIT_PORTION_MIN = 5;
const INIT_PORTION_MIDDLE = 8;
const INIT_PORTION_MAX = 12;

export {MAX_WIDTH, MIDDLE_WIDTH, PORTION_MAX, PORTION_MIN, INIT_PORTION_MAX, INIT_PORTION_MIDDLE, INIT_PORTION_MIN}; 